<?=$this->doctype('XHTML1_TRANSITIONAL')?>
<html xmlns="
http://www.w3.org/1999/xhtml
" lang="pt-br">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <base href="
http://
<?=$_SERVER['HTTP_HOST'] . $this->baseUrl()?>/" />
      <link type="text/css" rel="stylesheet" href="/css/stylesheet.css" />
      <title>Agenda</title>
   </head>
   <body>
      <div id="main">
         <div id="header">
            <h1>Agenda</h1>
         </div>
         <div id="sidebar">
            <ul>
               <li><a href="<?=$this->url(array("controller"=>"index","action"=>"index"),null,true)?>">Home</a></li>
               <li><a href="<?=$this->url(array("controller"=>"compromisso","action"=>"index"),null,true)?>">Contatos</a></li>
               <li><a href="<?=$this->url(array("controller"=>"sobre","action"=>"index"),null,true)?>">Sobre</a></li>
            </ul>
         </div>
         <div id="content">
            <?=$this->layout()->content?>
         </div>
      </div>
   </body>
</html>